

export const newCharacter = {
  // Character Info
  name: "",
  age: 0,
  species: "",
  culture: "",
  role: "",
  specialty: "",
  guild: "",
  guild_subject: "",
  free_subject: "",
  level: 0,
  // Mutable Character Info
  inventory: [
    "",
    "",
    "Backpack",
    "Water Canteen",
    "Bedroll",
    "Torch x2",
    "Fire Starter",
    "Rope",
    "Camp Shovel",
    "",
    "",
    "",
    "",
    "",
    "",
  ],
  current_health: 0,
  current_spark: 0,
  resource_used: 0,
  aid_used: 0,
  coins: 0,
  one_hand_equipped: false,
  two_hand_equipped: false,
  ranged_equipped: false,
}

export const demoCharacter = {
  // Immutable Character Info
  name: "Brellan Quickfoot",
  age: 17,
  species: "human",
  culture: "annieran",
  role: "cook",
  specialty: "way_of_pan",
  guild: "needlery",
  guild_subject: "word",
  free_subject: "none",
  level: 4,
  // Mutable Character Info
  inventory: [
    "Steel Wok",
    "",
    "Backpack",
    "Water Canteen",
    "Bedroll",
    "Torch x2",
    "Fire Starter",
    "Rope",
    "Camp Shovel",
    "",
    "",
    "",
    "",
    "",
    "",
  ],
  current_health: 9,
  current_spark: 2,
  resource_used: 2,
  aid_used: 0,
  coins: 15,
  one_hand_equipped: false,
  two_hand_equipped: false,
  ranged_equipped: false,
}