import { SpellList as spell } from "./SpellProvider";
import { SkillList as skill } from "./SkillProvider";

export const RoleList = {
  apothecary: {
    title: "Apothecary",
    brief: "A master at using ingredients of the world to thwart your enemies and aid your allies.",
    spell_name: "Flasks",
    resource_name: "ingredient",
    resources_name: "ingredients",
    start_coin: 20,
    level_1: {
      metrics: {
        max_health: 3,
        start_spark: 2,
        max_spark: 3,
        defense: 3,
        movement: 6,
        max_resource: 5,
        free_training: 0,
      },
      skills: [skill.apothecary.flasks],
      spells: [
        spell.apothecary.snottamus_extract,
        spell.apothecary.nouftus_mixture,
        spell.apothecary.choont_bomb,
        spell.apothecary.nectar_flask,
      ],
    },
    level_2: {
      metrics: {
        max_health: 4,
        start_spark: 2,
        max_spark: 4,
        defense: 3,
        movement: 6,
        max_resource: 5,
        free_training: 0,
      },
      skills: [skill.apothecary.flasks, skill.apothecary.flask_throwing],
      spells: [
        spell.apothecary.snottamus_extract,
        spell.apothecary.nouftus_mixture,
        spell.apothecary.choont_bomb,
        spell.apothecary.nectar_flask,
      ],
    },
    specialties: {
      alchemist: {
        name: "Alchemist",
        brief:"The alchemist specialty focuses on creature-based mixtures that harm enemies.",
        level_3: {
          metrics: {
            max_health: 5,
            start_spark: 3,
            max_spark: 4,
            defense: 3,
            movement: 6,
            max_resource: 6,
            free_training: 0,
          },
          skills: [
            skill.apothecary.flasks,
            skill.apothecary.flask_throwing,
            skill.apothecary.alchemist.improved_mixtures,
          ],
          spells: [
            spell.apothecary.snottamus_extract_plus,
            spell.apothecary.nouftus_mixture_plus,
            spell.apothecary.choont_bomb_plus,
            spell.apothecary.nectar_flask,
          ],
        },
        level_4: {
          metrics: {
            max_health: 6,
            start_spark: 3,
            max_spark: 5,
            defense: 3,
            movement: 6,
            max_resource: 7,
            free_training: 0,
          },
          skills: [
            skill.apothecary.flasks,
            skill.apothecary.flask_throwing,
            skill.apothecary.alchemist.improved_mixtures,
          ],
          spells: [
            spell.apothecary.snottamus_extract_plus,
            spell.apothecary.nouftus_mixture_plus,
            spell.apothecary.choont_bomb_plus,
            spell.apothecary.nectar_flask,
            spell.apothecary.rockroach_elixir,
          ],
        },
        level_5: {
          metrics: {
            max_health: 7,
            start_spark: 3,
            max_spark: 5,
            defense: 3,
            movement: 6,
            max_resource: 8,
            free_training: 1,
          },
          skills: [
            skill.apothecary.flasks,
            skill.apothecary.flask_throwing,
            skill.apothecary.alchemist.improved_mixtures,
            skill.apothecary.alchemist.bottle_bandolier,
          ],
          spells: [
            spell.apothecary.snottamus_extract_plus,
            spell.apothecary.nouftus_mixture_plus,
            spell.apothecary.choont_bomb_plus,
            spell.apothecary.nectar_flask,
            spell.apothecary.rockroach_elixir,
          ],
        },
        level_6: {
          metrics: {
            max_health: 8,
            start_spark: 3,
            max_spark: 6,
            defense: 3,
            movement: 6,
            max_resource: 9,
            free_training: 1,
          },
          skills: [
            skill.apothecary.flasks,
            skill.apothecary.flask_throwing,
            skill.apothecary.alchemist.improved_mixtures,
            skill.apothecary.alchemist.bottle_bandolier,
          ],
          spells: [
            spell.apothecary.snottamus_extract_plus,
            spell.apothecary.nouftus_mixture_plus,
            spell.apothecary.choont_bomb_plus,
            spell.apothecary.nectar_flask,
            spell.apothecary.rockroach_elixir,
            spell.apothecary.dragonmole_draught,
          ],
        },
      },
      herbalist: {
        name: "Herbalist",
        brief:"The herbalist specialty focuses on plant-based mixtures that support allies.",
        level_3: {
          metrics: {
            max_health: 5,
            start_spark: 3,
            max_spark: 4,
            defense: 3,
            movement: 6,
            max_resource: 6,
            free_training: 0,
          },
          skills: [skill.apothecary.flasks, skill.apothecary.flask_throwing],
          spells: [
            spell.apothecary.snottamus_extract,
            spell.apothecary.nouftus_mixture,
            spell.apothecary.choont_bomb,
            spell.apothecary.nectar_flask,
            spell.apothecary.skonk_grenade,
          ],
        },
        level_4: {
          metrics: {
            max_health: 6,
            start_spark: 3,
            max_spark: 5,
            defense: 3,
            movement: 6,
            max_resource: 7,
            free_training: 0,
          },
          skills: [skill.apothecary.flasks, skill.apothecary.flask_throwing],
          spells: [
            spell.apothecary.snottamus_extract,
            spell.apothecary.nouftus_mixture,
            spell.apothecary.choont_bomb,
            spell.apothecary.nectar_flask,
            spell.apothecary.skonk_grenade,
            spell.apothecary.super_grow,
          ],
        },
        level_5: {
          metrics: {
            max_health: 7,
            start_spark: 3,
            max_spark: 5,
            defense: 3,
            movement: 6,
            max_resource: 8,
            free_training: 1,
          },
          skills: [skill.apothecary.flasks, skill.apothecary.flask_throwing],
          spells: [
            spell.apothecary.snottamus_extract,
            spell.apothecary.nouftus_mixture,
            spell.apothecary.choont_bomb,
            spell.apothecary.nectar_flask,
            spell.apothecary.skonk_grenade,
            spell.apothecary.super_grow,
            spell.apothecary.silver_birch,
          ],
        },
        level_6: {
          metrics: {
            max_health: 8,
            start_spark: 3,
            max_spark: 6,
            defense: 3,
            movement: 6,
            max_resource: 9,
            free_training: 1,
          },
          skills: [skill.apothecary.flasks, skill.apothecary.flask_throwing],
          spells: [
            spell.apothecary.snottamus_extract,
            spell.apothecary.nouftus_mixture,
            spell.apothecary.choont_bomb,
            spell.apothecary.nectar_flask,
            spell.apothecary.skonk_grenade,
            spell.apothecary.super_grow,
            spell.apothecary.silver_birch,
            spell.apothecary.elmin_bark,
          ],
        },
      },
    },
  },
  bard: {
    title: "Bard",
    brief: "Your antics on the battlefield are as mesmerizing as your efforts off the field. A charming performer not to be underestimated.",
    spell_name: "Songs",
    resource_name: "verse",
    resources_name: "verses",
    start_coin: 20,
    level_1: {
      metrics: {
        max_health: 3,
        start_spark: 2,
        max_spark: 4,
        defense: 4,
        movement: 6,
        max_resource: 5,
        free_training: 0,
      },
      skills: [skill.bard.shared_inspiration, skill.bard.ancient_songs],
      spells: [
        spell.bard.dragons_wrath,
        spell.bard.kings_lament,
        spell.bard.guild_anthem,
      ],
    },
    level_2: {
      metrics: {
        max_health: 4,
        start_spark: 2,
        max_spark: 5,
        defense: 4,
        movement: 6,
        max_resource: 5,
        free_training: 0,
      },
      skills: [
        skill.bard.shared_inspiration,
        skill.bard.ancient_songs,
        skill.bard.in_tune,
      ],
      spells: [
        spell.bard.dragons_wrath,
        spell.bard.kings_lament,
        spell.bard.guild_anthem,
      ],
    },
    specialties: {
      song_master: {
        name: "Song Maiden/Master",
        brief:"The Song Maiden specialty focuses on supporting allies.",
        level_3: {
          metrics: {
            max_health: 5,
            start_spark: 3,
            max_spark: 5,
            defense: 4,
            movement: 6,
            max_resource: 6,
            free_training: 0,
          },
          skills: [
            skill.bard.shared_inspiration,
            skill.bard.ancient_songs,
            skill.bard.in_tune,
          ],
          spells: [
            spell.bard.dragons_wrath,
            spell.bard.kings_lament,
            spell.bard.guild_anthem,
            spell.bard.healing_song,
          ],
        },
        level_4: {
          metrics: {
            max_health: 6,
            start_spark: 3,
            max_spark: 6,
            defense: 4,
            movement: 6,
            max_resource: 7,
            free_training: 0,
          },
          skills: [
            skill.bard.shared_inspiration,
            skill.bard.ancient_songs,
            skill.bard.in_tune,
            skill.bard.song_master.mount_companion,
          ],
          spells: [
            spell.bard.dragons_wrath,
            spell.bard.kings_lament,
            spell.bard.guild_anthem,
            spell.bard.healing_song,
          ],
        },
        level_5: {
          metrics: {
            max_health: 7,
            start_spark: -1, // starting spark = max spark...
            max_spark: 6,
            defense: 4,
            movement: 6,
            max_resource: 8,
            free_training: 0,
          },
          skills: [
            skill.bard.shared_inspiration,
            skill.bard.ancient_songs,
            skill.bard.in_tune,
            skill.bard.song_master.mount_companion,
          ],
          spells: [
            spell.bard.dragons_wrath,
            spell.bard.kings_lament,
            spell.bard.guild_anthem,
            spell.bard.healing_song,
            spell.bard.yurgens_tune,
          ],
        },
        level_6: {
          metrics: {
            max_health: 8,
            start_spark: -1, // starting spark = max spark...
            max_spark: 7,
            defense: 4,
            movement: 6,
            max_resource: 9,
            free_training: 0,
          },
          skills: [
            skill.bard.shared_inspiration,
            skill.bard.ancient_songs,
            skill.bard.in_tune,
            skill.bard.song_master.mount_companion,
            skill.bard.song_master.encore,
          ],
          spells: [
            spell.bard.dragons_wrath,
            spell.bard.kings_lament_plus,
            spell.bard.guild_anthem_plus,
            spell.bard.healing_song_plus,
            spell.bard.yurgens_tune_plus,
          ],
        },
      },
      lore_wain: {
        name: "Lore Wain",
        brief:"The Lore Wain seeks to control situations (and creatures) with their wit and charm.",
        level_3: {
          metrics: {
            max_health: 5,
            start_spark: 3,
            max_spark: 5,
            defense: 4,
            movement: 6,
            max_resource: 6,
            free_training: 0,
          },
          skills: [
            skill.bard.shared_inspiration,
            skill.bard.ancient_songs,
            skill.bard.in_tune,
          ],
          spells: [
            spell.bard.dragons_wrath,
            spell.bard.kings_lament,
            spell.bard.guild_anthem,
            spell.bard.troll_charmer,
          ],
        },
        level_4: {
          metrics: {
            max_health: 6,
            start_spark: 3,
            max_spark: 6,
            defense: 4,
            movement: 6,
            max_resource: 7,
            free_training: 0,
          },
          skills: [
            skill.bard.shared_inspiration,
            skill.bard.ancient_songs,
            skill.bard.in_tune,
            skill.bard.lore_wain.melee_training,
            skill.bard.lore_wain.anti_spark,
          ],
          spells: [
            spell.bard.dragons_wrath,
            spell.bard.kings_lament,
            spell.bard.guild_anthem,
            spell.bard.troll_charmer,
          ],
        },
        level_5: {
          metrics: {
            max_health: 7,
            start_spark: -1, // start_spark = max_spark
            max_spark: 6,
            defense: 4,
            movement: 6,
            max_resource: 8,
            free_training: 0,
          },
          skills: [
            skill.bard.shared_inspiration,
            skill.bard.ancient_songs,
            skill.bard.in_tune,
            skill.bard.lore_wain.melee_training,
            skill.bard.lore_wain.anti_spark,
          ],
          spells: [
            spell.bard.dragons_wrath,
            spell.bard.kings_lament,
            spell.bard.guild_anthem,
            spell.bard.troll_charmer,
            spell.bard.armulyn,
          ],
        },
        level_6: {
          metrics: {
            max_health: 8,
            start_spark: -1, // start_spark = max_spark
            max_spark: 7,
            defense: 4,
            movement: 6,
            max_resource: 9,
            free_training: 0,
          },
          skills: [
            skill.bard.shared_inspiration,
            skill.bard.ancient_songs,
            skill.bard.in_tune,
            skill.bard.lore_wain.melee_training,
            skill.bard.lore_wain.anti_spark,
            skill.bard.lore_wain.lore_master,
          ],
          spells: [
            spell.bard.dragons_wrath,
            spell.bard.kings_lament,
            spell.bard.guild_anthem,
            spell.bard.troll_charmer,
            spell.bard.armulyn,
          ],
        },
      },
    },
  },
  cook: {
    title: "Cook",
    brief: "Never underestimate the power of a good meal. The cook is a well armored combatant, dishing up comfort and pain.",
    spell_name: "Snacks",
    resource_name: "ingredient",
    resources_name: "ingredients",
    start_coin: 25,
    level_1: {
      metrics: {
        max_health: 3,
        start_spark: 2,
        max_spark: 3,
        defense: 5,
        movement: 6,
        max_resource: 5,
        free_training: 0,
      },
      skills: [skill.cook.pot_luck, skill.cook.fireside, skill.cook.snack_pack],
      spells: [
        spell.cook.diggle_jerky,
        spell.cook.redberry_tea,
        spell.cook.fazzeldove_puff,
      ],
    },
    level_2: {
      metrics: {
        max_health: 4,
        start_spark: 2,
        max_spark: 4,
        defense: 5,
        movement: 6,
        max_resource: 5,
        free_training: 0,
      },
      skills: [
        skill.cook.pot_luck,
        skill.cook.fireside,
        skill.cook.snack_pack,
        skill.cook.fast_food,
        skill.cook.leftovers,
      ],
      spells: [
        spell.cook.diggle_jerky,
        spell.cook.redberry_tea,
        spell.cook.fazzeldove_puff,
        spell.cook.kiwicarrot_cake,
      ],
    },
    specialties: {
      way_of_pan: {
        name: "Way of the Pan",
        brief:"Way of the Pan is an in-your-face style cook with a focus on melee combat.",
        level_3: {
          metrics: {
            max_health: 6,
            start_spark: 3,
            max_spark: 4,
            defense: 5,
            movement: 6,
            max_resource: 6,
            free_training: 0,
          },
          skills: [
            skill.cook.pot_luck,
            skill.cook.fireside,
            skill.cook.snack_pack,
            skill.cook.fast_food,
            skill.cook.leftovers,
            skill.cook.way_of_pan.giant_utensil,
          ],
          spells: [
            spell.cook.diggle_jerky,
            spell.cook.redberry_tea,
            spell.cook.fazzeldove_puff,
            spell.cook.kiwicarrot_cake,
          ],
        },
        level_4: {
          metrics: {
            max_health: 7,
            start_spark: 3,
            max_spark: 5,
            defense: 5,
            movement: 6,
            max_resource: 7,
            free_training: 0,
          },
          skills: [
            skill.cook.pot_luck,
            skill.cook.fireside,
            skill.cook.snack_pack,
            skill.cook.fast_food,
            skill.cook.leftovers,
            skill.cook.way_of_pan.giant_utensil,
            skill.cook.way_of_pan.salt_pepper,
          ],
          spells: [
            spell.cook.diggle_jerky,
            spell.cook.redberry_tea,
            spell.cook.fazzeldove_puff,
            spell.cook.kiwicarrot_cake,
          ],
        },
        level_5: {
          metrics: {
            max_health: 9,
            start_spark: 3,
            max_spark: 5,
            defense: 5,
            movement: 7,
            max_resource: 7,
            free_training: 0,
          },
          skills: [
            skill.cook.pot_luck,
            skill.cook.fireside,
            skill.cook.snack_pack,
            skill.cook.fast_food,
            skill.cook.leftovers,
            skill.cook.way_of_pan.giant_utensil,
            skill.cook.way_of_pan.salt_pepper,
          ],
          spells: [
            spell.cook.diggle_jerky,
            spell.cook.redberry_tea,
            spell.cook.fazzeldove_puff,
            spell.cook.kiwicarrot_cake,
            spell.cook.octurtle_surprise,
          ],
        },
        level_6: {
          metrics: {
            max_health: 11,
            start_spark: 3,
            max_spark: 6,
            defense: 5,
            movement: 7,
            max_resource: 8,
            free_training: 0,
          },
          skills: [
            skill.cook.pot_luck,
            skill.cook.fireside,
            skill.cook.snack_pack,
            skill.cook.fast_food,
            skill.cook.leftovers,
            skill.cook.way_of_pan.giant_utensil,
            skill.cook.way_of_pan.salt_pepper,
            skill.cook.way_of_pan.good_cook,
          ],
          spells: [
            spell.cook.diggle_jerky_plus,
            spell.cook.redberry_tea_plus,
            spell.cook.fazzeldove_puff_plus,
            spell.cook.kiwicarrot_cake_plus,
            spell.cook.octurtle_surprise_plus,
          ],
        },
      },
      way_of_ladle: {
        name: "Way of the Ladle",
        brief:"Way of the Ladle is for the cook that’d rather toss scaulding soups on their enemies from a distance.",
        level_3: {
          metrics: {
            max_health: 5,
            start_spark: 3,
            max_spark: 4,
            defense: 5,
            movement: 6,
            max_resource: 6,
            free_training: 0,
          },
          skills: [
            skill.cook.pot_luck,
            skill.cook.fireside,
            skill.cook.snack_pack,
            skill.cook.fast_food,
            skill.cook.leftovers,
            skill.cook.way_of_ladle.food_fighter,
          ],
          spells: [
            spell.cook.diggle_jerky_range,
            spell.cook.redberry_tea_range,
            spell.cook.fazzeldove_puff_range,
            spell.cook.kiwicarrot_cake_range,
          ],
        },
        level_4: {
          metrics: {
            max_health: 7,
            start_spark: 3,
            max_spark: 5,
            defense: 5,
            movement: 6,
            max_resource: 7,
            free_training: 0,
          },
          skills: [
            skill.cook.pot_luck,
            skill.cook.fireside,
            skill.cook.snack_pack,
            skill.cook.fast_food,
            skill.cook.leftovers,
            skill.cook.way_of_ladle.food_fighter,
          ],
          spells: [
            spell.cook.diggle_jerky_range,
            spell.cook.redberry_tea_range,
            spell.cook.fazzeldove_puff_range,
            spell.cook.kiwicarrot_cake_range,
            spell.cook.brayble_cake,
          ],
        },
        level_5: {
          metrics: {
            max_health: 8,
            start_spark: 3,
            max_spark: 5,
            defense: 5,
            movement: 6,
            max_resource: 8,
            free_training: 1,
          },
          skills: [
            skill.cook.pot_luck,
            skill.cook.fireside,
            skill.cook.snack_pack,
            skill.cook.fast_food,
            skill.cook.leftovers,
            skill.cook.way_of_ladle.food_fighter,
          ],
          spells: [
            spell.cook.diggle_jerky_range,
            spell.cook.redberry_tea_range,
            spell.cook.fazzeldove_puff_range,
            spell.cook.kiwicarrot_cake_range,
            spell.cook.brayble_cake,
            spell.cook.twaidge_root,
          ],
        },
        level_6: {
          metrics: {
            max_health: 9,
            start_spark: 3,
            max_spark: 6,
            defense: 5,
            movement: 6,
            max_resource: 9,
            free_training: 1,
          },
          skills: [
            skill.cook.pot_luck,
            skill.cook.fireside,
            skill.cook.snack_pack,
            skill.cook.fast_food,
            skill.cook.leftovers,
            skill.cook.way_of_ladle.food_fighter,
            skill.cook.way_of_ladle.short_order,
          ],
          spells: [
            spell.cook.diggle_jerky_range,
            spell.cook.redberry_tea_range,
            spell.cook.fazzeldove_puff_range,
            spell.cook.kiwicarrot_cake_range,
            spell.cook.brayble_cake,
            spell.cook.twaidge_root,
          ],
        },
      },
    },
  },
  ranger: {
    title: "Ranger",
    brief: "An expert tracker and ranged fighter. Can be in the backline or right under your nose!",
    spell_name: "",
    resource_name: "",
    start_coin: 10,
    level_1: {
      metrics: {
        max_health: 3,
        start_spark: 2,
        max_spark: 3,
        defense: 4,
        movement: 6,
        max_resource: 0,
        free_training: 0,
      },
      skills: [skill.ranger.tracker, skill.ranger.ambush],
    },
    level_2: {
      metrics: {
        max_health: 4,
        start_spark: 2,
        max_spark: 4,
        defense: 4,
        movement: 6,
        max_resource: 0,
        free_training: 0,
      },
      skills: [skill.ranger.tracker, skill.ranger.ambush, skill.ranger.archery],
    },
    specialties: {
      scout: {
        name: "Scout",
        brief:"The scout has mastered their skills in ranged combat.",
        level_3: {
          metrics: {
            max_health: 5,
            start_spark: 3,
            max_spark: 4,
            defense: 4,
            movement: 6,
            max_resource: 0,
            free_training: 0,
          },
          skills: [
            skill.ranger.tracker,
            skill.ranger.scout.improved_ambush,
            skill.ranger.archery,
          ],
        },
        level_4: {
          metrics: {
            max_health: 6,
            start_spark: 3,
            max_spark: 5,
            defense: 4,
            movement: 6,
            max_resource: 0,
            free_training: 0,
          },
          skills: [
            skill.ranger.tracker,
            skill.ranger.scout.improved_ambush,
            skill.ranger.archery,
            skill.ranger.scout.quick_study,
            skill.ranger.scout.woodsman,
          ],
        },
        level_5: {
          metrics: {
            max_health: 7,
            start_spark: 3,
            max_spark: 5,
            defense: 4,
            movement: 6,
            max_resource: 0,
            free_training: 1,
          },
          skills: [
            skill.ranger.tracker,
            skill.ranger.scout.improved_ambush,
            skill.ranger.archery,
            skill.ranger.scout.quick_study,
            skill.ranger.scout.woodsman,
            skill.ranger.scout.momentum,
          ],
        },
        level_6: {
          metrics: {
            max_health: 8,
            start_spark: 3,
            max_spark: 6,
            defense: 4,
            movement: 6,
            max_resource: 0,
            free_training: 1,
          },
          skills: [
            skill.ranger.tracker,
            skill.ranger.scout.improved_ambush,
            skill.ranger.archery,
            skill.ranger.scout.quick_study,
            skill.ranger.scout.woodsman,
            skill.ranger.scout.momentum,
            skill.ranger.scout.multishot,
          ],
        },
      },
      beast_guardian: {
        name: "Beast Guardian",
        brief:"The Beast Guardian has made a special bond with a creature that aids them in their adventure.",
        level_3: {
          metrics: {
            max_health: 5,
            start_spark: 3,
            max_spark: 4,
            defense: 4,
            movement: 6,
            max_resource: 0,
            free_training: 0,
          },
          skills: [
            skill.ranger.tracker,
            skill.ranger.archery,
            skill.ranger.beast_guardian.beast_companion_lvl_3,
          ],
        },
        level_4: {
          metrics: {
            max_health: 6,
            start_spark: 3,
            max_spark: 5,
            defense: 4,
            movement: 6,
            max_resource: 0,
            free_training: 0,
          },
          skills: [
            skill.ranger.tracker,
            skill.ranger.archery,
            skill.ranger.beast_guardian.beast_companion_lvl_4,
            skill.ranger.beast_guardian.beast_sense,
            skill.ranger.beast_guardian.mend,
          ],
        },
        level_5: {
          metrics: {
            max_health: 7,
            start_spark: 3,
            max_spark: 5,
            defense: 4,
            movement: 7,
            max_resource: 0,
            free_training: 1,
          },
          skills: [
            skill.ranger.tracker,
            skill.ranger.archery,
            skill.ranger.beast_guardian.beast_companion_lvl_4,
            skill.ranger.beast_guardian.beast_sense,
            skill.ranger.beast_guardian.mend,
            skill.ranger.beast_guardian.melee_training,
          ],
        },
        level_6: {
          metrics: {
            max_health: 8,
            start_spark: 3,
            max_spark: 6,
            defense: 4,
            movement: 7,
            max_resource: 0,
            free_training: 1,
          },
          skills: [
            skill.ranger.tracker,
            skill.ranger.archery,
            skill.ranger.beast_guardian.beast_companion_lvl_6,
            skill.ranger.beast_guardian.beast_sense,
            skill.ranger.beast_guardian.mend,
            skill.ranger.beast_guardian.melee_training,
            skill.ranger.beast_guardian.new_tricks,
          ],
        },
      },
    },
  },
  scoundrel: {
    title: "Scoundrel",
    brief: "Whether on the open seas or living life with the landlubbers, scoundrels are often quick and cunning companions.",
    spell_name: "",
    resource_name: "",
    start_coin: 25,
    level_1: {
      metrics: {
        max_health: 4,
        start_spark: 2,
        max_spark: 3,
        defense: 3,
        movement: 6,
        max_resource: 0,
        free_training: 0,
      },
      skills: [skill.scoundrel.trade_tricks, skill.scoundrel.flank],
      spells: [],
    },
    level_2: {
      metrics: {
        max_health: 5,
        start_spark: 2,
        max_spark: 4,
        defense: 3,
        movement: 6,
        max_resource: 0,
        free_training: 0,
      },
      skills: [
        skill.scoundrel.trade_tricks,
        skill.scoundrel.flank,
        skill.scoundrel.exploit_weakness,
      ],
      spells: [],
    },
    specialties: {
      spy: {
        name: "Spy",
        brief:"The spy favors the stealthy approach, avoids damage, and strikes from the shadows.",
        level_3: {
          metrics: {
            max_health: 6,
            start_spark: 3,
            max_spark: 4,
            defense: 3,
            movement: 7,
            max_resource: 0,
            free_training: 0,
          },
          skills: [
            skill.scoundrel.trade_tricks,
            skill.scoundrel.flank,
            skill.scoundrel.exploit_weakness,
            skill.scoundrel.spy.dodge,
          ],
          spells: [],
        },
        level_4: {
          metrics: {
            max_health: 8,
            start_spark: 3,
            max_spark: 6,
            defense: 3,
            movement: 7,
            max_resource: 0,
            free_training: 0,
          },
          skills: [
            skill.scoundrel.trade_tricks,
            skill.scoundrel.flank,
            skill.scoundrel.exploit_weakness,
            skill.scoundrel.spy.dodge,
            skill.scoundrel.spy.stalk,
            skill.scoundrel.spy.well_connected,
          ],
          spells: [],
        },
        level_5: {
          metrics: {
            max_health: 9,
            start_spark: 3,
            max_spark: 6,
            defense: 3,
            movement: 8,
            max_resource: 0,
            free_training: 1,
          },
          skills: [
            skill.scoundrel.trade_tricks,
            skill.scoundrel.flank,
            skill.scoundrel.exploit_weakness,
            skill.scoundrel.spy.dodge,
            skill.scoundrel.spy.stalk,
            skill.scoundrel.spy.well_connected,
            skill.scoundrel.spy.pilfer,
          ],
          spells: [],
        },
        level_6: {
          metrics: {
            max_health: 10,
            start_spark: 3,
            max_spark: 7,
            defense: 3,
            movement: 8,
            max_resource: 0,
            free_training: 1,
          },
          skills: [
            skill.scoundrel.trade_tricks,
            skill.scoundrel.flank,
            skill.scoundrel.exploit_weakness,
            skill.scoundrel.spy.dodge,
            skill.scoundrel.spy.stalk,
            skill.scoundrel.spy.well_connected,
            skill.scoundrel.spy.pilfer,
            skill.scoundrel.spy.dagger_operative,
          ],
          spells: [],
        },
      },
      pirate: {
        name: "Pirate",
        brief:"The pirate is a brute force, taking challenges head-on with little regard for their own safety.",
        level_3: {
          metrics: {
            max_health: 7,
            start_spark: 3,
            max_spark: 4,
            defense: 3,
            movement: 6,
            max_resource: 0,
            free_training: 0,
          },
          skills: [
            skill.scoundrel.trade_tricks,
            skill.scoundrel.flank,
            skill.scoundrel.exploit_weakness,
            skill.scoundrel.pirate.rage,
            skill.scoundrel.pirate.sea_worthy,
          ],
          spells: [],
        },
        level_4: {
          metrics: {
            max_health: 10,
            start_spark: 3,
            max_spark: 5,
            defense: 3,
            movement: 6,
            max_resource: 0,
            free_training: 0,
          },
          skills: [
            skill.scoundrel.trade_tricks,
            skill.scoundrel.flank,
            skill.scoundrel.exploit_weakness,
            skill.scoundrel.pirate.rage,
            skill.scoundrel.pirate.sea_worthy,
            skill.scoundrel.pirate.combat_training,
            skill.scoundrel.pirate.inspiring_presence,
          ],
          spells: [],
        },
        level_5: {
          metrics: {
            max_health: 12,
            start_spark: 3,
            max_spark: 5,
            defense: 3,
            movement: 7,
            max_resource: 0,
            free_training: 1,
          },
          skills: [
            skill.scoundrel.trade_tricks,
            skill.scoundrel.flank,
            skill.scoundrel.exploit_weakness,
            skill.scoundrel.pirate.rage,
            skill.scoundrel.pirate.sea_worthy,
            skill.scoundrel.pirate.combat_training,
            skill.scoundrel.pirate.inspiring_presence,
            skill.scoundrel.pirate.reactive,
          ],
          spells: [],
        },
        level_6: {
          metrics: {
            max_health: 14,
            start_spark: 3,
            max_spark: 6,
            defense: 3,
            movement: 7,
            max_resource: 0,
            free_training: 1,
          },
          skills: [
            skill.scoundrel.trade_tricks,
            skill.scoundrel.flank,
            skill.scoundrel.exploit_weakness,
            skill.scoundrel.pirate.rage,
            skill.scoundrel.pirate.sea_worthy,
            skill.scoundrel.pirate.combat_training,
            skill.scoundrel.pirate.inspiring_presence,
            skill.scoundrel.pirate.reactive,
            skill.scoundrel.pirate.parry,
          ],
          spells: [],
        },
      },
    },
  },
  warden: {
    title: "Warden",
    brief: "Skilled in armor and weapons; few can contend with the warden in hand-to-hand combat.",
    spell_name: "",
    resource_name: "",
    start_coin: 15,
    level_1: {
      metrics: {
        max_health: 4,
        start_spark: 2,
        max_spark: 3,
        defense: 5,
        movement: 6,
        max_resource: 0,
        free_training: 0,
      },
      skills: [skill.warden.shield_training, skill.warden.adaptable],
      spells: [],
    },
    level_2: {
      metrics: {
        max_health: 5,
        start_spark: 2,
        max_spark: 4,
        defense: 5,
        movement: 6,
        max_resource: 0,
        free_training: 0,
      },
      skills: [
        skill.warden.shield_training,
        skill.warden.adaptable,
        skill.warden.weapon_training,
      ],
      spells: [],
    },
    specialties: {
      arms_master: {
        name: "Arms Master",
        brief:"The arms master specializes in using a two-handed weapon to dominate the battle field.",
        level_3: {
          metrics: {
            max_health: 6,
            start_spark: 3,
            max_spark: 4,
            defense: 5,
            movement: 6,
            max_resource: 0,
            free_training: 0,
          },
          skills: [
            skill.warden.shield_training,
            skill.warden.adaptable,
            skill.warden.weapon_training,
            skill.warden.arms_master.heavy_handed,
          ],
          spells: [],
        },
        level_4: {
          metrics: {
            max_health: 7,
            start_spark: 3,
            max_spark: 5,
            defense: 5,
            movement: 6,
            max_resource: 0,
            free_training: 0,
          },
          skills: [
            skill.warden.shield_training,
            skill.warden.adaptable,
            skill.warden.weapon_training,
            skill.warden.arms_master.heavy_handed,
            skill.warden.arms_master.cleave,
          ],
          spells: [],
        },
        level_5: {
          metrics: {
            max_health: 9,
            start_spark: 3,
            max_spark: 5,
            defense: 5,
            movement: 8,
            max_resource: 0,
            free_training: 1,
          },
          skills: [
            skill.warden.shield_training,
            skill.warden.adaptable,
            skill.warden.weapon_training,
            skill.warden.arms_master.heavy_handed,
            skill.warden.arms_master.cleave,
            skill.warden.arms_master.strength_conditioning,
          ],
          spells: [],
        },
        level_6: {
          metrics: {
            max_health: 10,
            start_spark: 3,
            max_spark: 6,
            defense: 5,
            movement: 8,
            max_resource: 0,
            free_training: 1,
          },
          skills: [
            skill.warden.shield_training,
            skill.warden.adaptable,
            skill.warden.weapon_training,
            skill.warden.arms_master.heavy_handed,
            skill.warden.arms_master.cleave,
            skill.warden.arms_master.strength_conditioning,
            skill.warden.arms_master.second_attack,
          ],
          spells: [],
        },
      },
      protector: {
        name: "Protector",
        brief:"The protector is a defensive specialist. A defender of their companions, and guardian of the realm.",
        level_3: {
          metrics: {
            max_health: 7,
            start_spark: 3,
            max_spark: 4,
            defense: 5,
            movement: 6,
            max_resource: 0,
            free_training: 0,
          },
          skills: [
            skill.warden.shield_training,
            skill.warden.adaptable,
            skill.warden.weapon_training,
            skill.warden.protector.defensive_stance,
            skill.warden.protector.offensive_stance,
          ],
          spells: [],
        },
        level_4: {
          metrics: {
            max_health: 9,
            start_spark: 3,
            max_spark: 5,
            defense: 5,
            movement: 6,
            max_resource: 0,
            free_training: 0,
          },
          skills: [
            skill.warden.shield_training,
            skill.warden.adaptable,
            skill.warden.weapon_training,
            skill.warden.protector.defensive_stance,
            skill.warden.protector.offensive_stance,
            skill.warden.protector.improved_shield_training,
          ],
          spells: [],
        },
        level_5: {
          metrics: {
            max_health: 11,
            start_spark: 3,
            max_spark: 5,
            defense: 5,
            movement: 7,
            max_resource: 0,
            free_training: 1,
          },
          skills: [
            skill.warden.shield_training,
            skill.warden.adaptable,
            skill.warden.weapon_training,
            skill.warden.protector.defensive_stance,
            skill.warden.protector.offensive_stance,
            skill.warden.protector.improved_shield_training,
            skill.warden.protector.taunt,
          ],
          spells: [],
        },
        level_6: {
          metrics: {
            max_health: 12,
            start_spark: 3,
            max_spark: 6,
            defense: 5,
            movement: 7,
            max_resource: 0,
            free_training: 1,
          },
          skills: [
            skill.warden.shield_training,
            skill.warden.adaptable,
            skill.warden.weapon_training,
            skill.warden.protector.defensive_stance,
            skill.warden.protector.offensive_stance,
            skill.warden.protector.improved_shield_training,
            skill.warden.protector.taunt,
            skill.warden.protector.warding_bond,
          ],
          spells: [],
        },
      },
    },
  },
};
