export const SubjectList = {
    word:{
      name:"Word",
      is_thag:true,
      description:""
    },
    form:{
      name:"Form",
      is_thag:true,
      description:""
    },
    song:{
      name:"Song",
      is_thag:true,
      description:""
    },
    athletistry:{
      name:"Athletistry",
      is_thag:false,
      description:""
    },
    bushcraft:{
      name:"Bushcraft",
      is_thag:false,
      description:""
    },
    critterspeak:{
      name:"Critterspeak",
      is_thag:false,
      description:""
    },
    medicineship:{
      name:"Medicineship",
      is_thag:false,
      description:""
    },
    smarts:{
      name:"Smarts",
      is_thag:false,
      description:""
    },
    sneakery:{
      name:"Sneakery",
      is_thag:false,
      description:""
    },
    tinkersmith:{
      name:"Tinkersmith",
      is_thag:false,
      description:""
    },
    one_handed:{
      name:"One Handed Weapons",
      is_thag:false,
      description:""
    },
    two_handed:{
      name:"Two Handed Weapons",
      is_thag:false,
      description:""
    },
    ranged:{
      name:"Ranged Weapons",
      is_thag:false,
      description:""
    }
  }
